pipeline {
  agent none
  stages {
    stage('Checkout Code') {
      agent any
      steps {
        // Checkout the code from the repository
        checkout scm
      }
    }
    stage('Back-end Build') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'mvn clean compile'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
